spring.application.name=kisan_setu
spring.datasource.url=jdbc:postgresql://localhost:5432/kisan_setu_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
server.address=0.0.0.0
