# DATABASE CONFIG
spring.application.name=kisan_setu
spring.datasource.url=jdbc:postgresql://localhost:5432/kisan_setu_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SERVER CONFIG
server.port=8080
server.address=0.0.0.0

#FILE UPLOAD
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



# JWT CONFIG
jwt.secret=4f3s9kQ8vQ1vZ7n2mQx8q7cL0k8p8y9aQmZp0bQk8eA=
jwt.access.expiration=900000
jwt.refresh.expiration=64000008

auth.cookie.secure=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shahkriya2911@gmail.com
spring.mail.password=hoacuewdmqdzuehp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#admin secret
app.admin.secret=adminKisanSetu@321
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.data.web.pageable.default-page-size=6

# Jackson date/time serialization - use timestamp arrays [year,month,day,hour,min,sec,nano]
spring.jackson.serialization.write-dates-as-timestamps=true
#Swagger - http://localhost:8080/swagger-ui/index.html
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379